### ISSUE TITLE
Segmentation error in simulation

### ISSUE THREAD

**Issue by frontzekkarl** [skovaka/UNCALLED#22]
Hello

I am running the simulation with an unrelated control experiment and keep getting the error 32589 Segmentation fault      (core dumped). Any ideas how to solve this?

This is my input

uncalled sim SARS2 /fast5 --ctl-seqsum sequencing_summary.txt --unc-seqsum 20190809_zymo_seqsum.txt --unc-paf 20190809_zymo_uncalled.paf -t 4 --enrich -c 3 --sim-speed 0.25 > uncalled_out.paf 2> uncalled_err.txt

This is the uncalled_err.txt

Loading UNCALLED PAF............
'================================
Procesing run...................
Generating pattern..............
'================================

Loading control PAF.............
'================================
Procesing run...................
Ordering reads..................
================================0 loaded

Any help very much appreciated.

Karl

**Comment by skovaka** [comment]
Hi,

Are you sure your fast5 files are at "/fast5" (at the filesystem root), and not something like "./fast5"? If it is supposed to be "/fast5", is that a directory or text file? If it's a text file, then the issue is that the code thinks it's a fast5 file because it ends in "fast5". I should change that to check for ".fast5" instead, but for now you could try renaming it to something like "fast5s.txt" and see if that works. If it is a directory that exists and contains fast5 files then I'm not sure what the error is, in which case let me know and I'll keep digging.

Thanks,
Sam

**Comment by frontzekkarl** [comment]
Hi 

Sorry for the confusion, it's actually like this

uncalled sim SARS2 /home/ubuntu/KFEX331/KFEX302_1/fast5 --ctl-seqsum /home/ubuntu/KFEX331/KFEX302_1/basecall/sequencing_summary.txt --unc-seqsum 20190809_zymo_seqsum.txt  --unc-paf 20190809_zymo_uncalled.paf -t 4 --enrich -c 3 --sim-speed 0.25 > uncalled_out.paf 2> uncalled_err.txt

so I don't think the root folder is the issue here. Actually, there's a different error (34607 Segmentation fault) when I provide a folder without fast5. 

I will proceed with the actual UNCALLED anyway.

Thank you, Karl

**Comment by frontzekkarl** [comment]
I've set up a dedicated UNCALLED PC and decided to go on with the UNCALLED regardless and it worked.
