### ISSUE TITLE
Regarding library prep for UNCALLED sequencing

### ISSUE THREAD

**Issue by idahoijer** [skovaka/UNCALLED#26]
Hi,

We are about to try UNCALLED for the first time, and I have a couple of questions regarding the library preparation.

1. What is the recommended DNA input?
2. In the paper, SQK-LSK109 was used. Would SQK-LSK110 work just as well?
3. What is the reason you excluded the DNA CS and FFPE end repair in the library prep in the paper?

I'm very excited to try this method. Thanks for sharing such great work!

**Comment by skovaka** [comment]
Here are responses from my co-author Yunfan Fan who did all of the library prep:

1. We stuck with the recommended ~1ug/ul for each library prep.
2. I think LSK110 should be okay, though I don’t know of anyone who’s actually tried it. My impression is that the library prep kit versions don’t change the electrical signal that drastically, since the ONT basecalling models are the same for both. 
3. The DNA CS is helpful for troubleshooting a sample vs flowcell failure if the run goes bad, but if the sample/extraction method has worked well before, we usually exclude it. We found that the FFPE repair doesn’t really improve the run quality for many of our samples, especially if the DNA freshly extracted and has not gone through many freeze/thaw cycles, so we exclude that as well and replace the lost volume by using 50ul of sample and 7ul of End-prep reaction buffer. FFPE might be helpful for older DNA, or for samples where the extraction method is not as robust.

Hope that helps!

**Comment by idahoijer** [comment]
Thanks Sam and Yunfan! That helps a lot.
