### ISSUE TITLE
AttributeError: 'uncalled.minknow_client' has no attribute 'Client' 

### ISSUE THREAD

**Issue by MayerMarvin** [skovaka/UNCALLED#30]
Hello,

I am trying to install UNCALLED on a Linux 64 bit system with Ubuntu 18.4 in an Anaconda environment. The uncalled index and uncalled map functions have been tested and are working fine. However, as soon as I want to test realtime enrichment for uncalled, I get the following error message:

```
uncalled realtime LTR12_DNA_sequence.fa --port 8000 -t 16 -c 3 --enrich > out.paf
Traceback (most recent call last):
  File "/home/nanopore/.local/bin/uncalled", line 196, in realtime_cmd
    client = unc.minknow_client.Client(conf.host, conf.port, conf.chunk_time, conf.num_channels)
AttributeError: module 'uncalled.minknow_client' has no attribute 'Client'
```

Expected behavior:
```
> uncalled realtime E.coli --port 8000 -t 16 --enrich -c 3 > uncalled_out.paf 
Starting client
Starting mappers
Mapping
```

All needed packages were installed using the latest release:
```
python3 -m pip list
Package     Version
----------- -------------------
certifi     2020.6.20
chardet     4.0.0
grpcio      1.36.1
idna        2.10
minknow-api 4.1.5
mkl-fft     1.3.0
mkl-random  1.1.1
mkl-service 2.3.0
numpy       1.19.2
packaging   20.9
pip         21.0.1
protobuf    3.15.5
pybind11    2.6.2
pyparsing   2.4.7
python-git  2018.2.1
read-until  3.0.0
requests    2.25.1
Send2Trash  1.5.0
setuptools  52.0.0.post20210125
six         1.15.0
uncalled    2.2
urllib3     1.26.3
wheel       0.36.2
```

Am I missing something during the installation of uncalled?
Any help would be very much appreciated!

Cheers,
Marvin

**Comment by skovaka** [comment]
Weird, I don't get that error. Have you ever installed an older version of UNCALLED? If so, the "uncalled" command could be using a different version of python associated with an old UNCALLED version for some reason.

Try running these commands in an interactive python3 session:
```
$ python3
>>> import uncalled
>>> print(uncalled.minknow_client.Client)
```
For me that prints `<class 'uncalled.minknow_client.Client'>`. If that works, then you could try running uncalled from a script in the cloned repo. So if you clone this repo to `<path>/UNCALLED`, run `<path>/UNCALLED/scripts/uncalled realtime LTR12_DNA_sequence.fa ...`. You don't need to have an active sequencing run for this test, since I believe your error should come up before that point.

**Comment by MayerMarvin** [comment]
It seems that the problem was really due to an incompatible combination of the uncalled and python versions. I was able to resolve this problem by uninstalling and reinstalling uncalled. The uncalled realtime function is currently working again.
