### ISSUE TITLE
barcodes

### ISSUE THREAD

**Issue by ramoya** [skovaka/UNCALLED#34]
Does UNCALLED handle barcoded samples? Meaning, does it exclude barcodes in k-mer search of the reference? Does it demultiplex reads into separate files? #32 had some info but these answers weren't clear to me

**Comment by skovaka** [comment]
No, we don't currently have an option to skip barcodes. I haven't tried running UNCALLED on barcoded samples, but I don't think they would reduce the mapping rate very much because the sequences are short and a bit of unalignable signal isn't a big problem. The only major issue I can envision is false positives if the any barcodes happen to match a sequence in your target reference. You could fix that by aligning the barcode sequences to your reference and masking hits by replacing the sequences with "N"s. I'll try to do some testing with this and maybe try adding an option to skips barcodes in the future.
