### ISSUE TITLE
Computer requirement for UNCALLED

### ISSUE THREAD

**Issue by ylang0825** [skovaka/UNCALLED#52]
Hello everyone,
I used UNCALLED to enrich a set of genes (repeat masked already) of human genome, a total of 46M in size. When I performed this experiment on a used flowcell with 118 pores usable, UNCALLED is running well, ejecting 7471 reads from all 36449 reads (it seemed much fewer than expectation). However, when I performed this on a new flowcell with >1200 pores usable, I found few reads were ejected (51 reads of 17410 reads in first 15 minutes). I looked into the sequencing summary text and found reads were no longer ejected after 6 minutes. The occupied memory was larger and larger, and finally UNCALLED was killed by the system. It seemed UNCALLED was stuck in some process. The computer has UBUNTU 16.04 with 16 cores and 16G memory and 1T storage. I wonder whether the computer hardware was enough for this UNCALLED task? Or  there's something I did wrong? 

Thank you！

**Comment by skovaka** [comment]
Sorry for the issue, and the delayed response. Your computer sounds like it should be sufficient to run UNCALLED, and I'm not sure what is going wrong. Does your computer have 16 physical cores, or 8 cores and 16 threads? If it's the latter, you could try using only 8 threads in case 16 is using too much memory or something. Since these issues are difficult to debug remotely, you may want to try ONT's builtin adaptive sampling mode if you have a GPU, which use basecalling rather than direct raw signal alignment for the same application.
