### ISSUE TITLE
Error when trying example

### ISSUE THREAD

**Issue by peiyihe** [skovaka/UNCALLED#58]
Hi,

I have followed the guide in readme, but when I want to try example in example file, it still meets some problem like this
<img width="1036" alt="屏幕截图_20240307_193237" src="https://github.com/skovaka/UNCALLED/assets/52478488/93e91bf3-cec8-46be-8788-1578199aef13">
I'm very confused, thanks!

**Comment by skovaka** [comment]
It looks like a C++ linking error. What operating system are you using, and what is your GCC verison (`gcc -v`)?

**Comment by peiyihe** [comment]
> It looks like a C++ linking error. What operating system are you using, and what is your GCC verison (`gcc -v`)?

Thanks for your reply!  My gcc version is 9.4.0 (Ubuntu 9.4.0-1ubuntu1~20.04.2)

**Comment by skovaka** [comment]
Interesting, those are the exact same versions of my OS and gcc. It looks like you're using conda, so the issue could be that conda is compiling with different libraries than your OS uses to run the program, which has happened to me and others in similar projects (https://github.com/pybind/pybind11/issues/3623)

You could try re-installing UNCALLED with `python3 -m pip install .`, and then in the examples replace `uncalled ...` with `python3 -m uncalled ...` to make sure it's using the same python version. If that doesn't work, try making a new conda environment, or maybe try re-installing conda. Sorry for the trouble, and hope that helps!

If you have any more issues, could you copy and paste the install/run commands and error message, instead of a screenshot? That will be easier to copy for me. 

Thanks,
Sam

**Comment by peiyihe** [comment]
Hi Sam,

Thank you for your thoughtful response. Despite following your suggestions, I'm still encountering some difficulties. I copy all my commands and maybe you could help me to see whether something is wrong.
`pyhe@PYHE_VM:~$ pip3 uninstall uncalled
Found existing installation: uncalled 2.3.0
Uninstalling uncalled-2.3.0:
  Would remove:
    /home/pyhe/anaconda3/bin/uncalled
    /home/pyhe/anaconda3/lib/python3.7/site-packages/_uncalled.cpython-37m-x86_64-linux-gnu.so
    /home/pyhe/anaconda3/lib/python3.7/site-packages/uncalled-2.3.0.dist-info/*
    /home/pyhe/anaconda3/lib/python3.7/site-packages/uncalled/*
Proceed (Y/n)? Y
  Successfully uninstalled uncalled-2.3.0
pyhe@PYHE_VM:~$ cd anaconda3
pyhe@PYHE_VM:~/anaconda3$ activate uncalled
-bash: /home/pyhe/anaconda3/bin/activate: Permission denied
pyhe@PYHE_VM:~/anaconda3$ conda activate uncalled
(uncalled) pyhe@PYHE_VM:~/anaconda3$ cd ..
(uncalled) pyhe@PYHE_VM:~$ cd UNCALLED
(uncalled) pyhe@PYHE_VM:~/UNCALLED$ python3 -m pip install .
Processing /home/pyhe/UNCALLED
  Preparing metadata (setup.py) ... done
Requirement already satisfied: read-until==3.0.0 in /home/pyhe/anaconda3/lib/python3.7/site-packages/read_until-3.0.0-py3.7.egg (from uncalled==2.3.0) (3.0.0)
Requirement already satisfied: minknow-api>=5.0 in /home/pyhe/.local/lib/python3.7/site-packages (from uncalled==2.3.0) (5.5.2)
Requirement already satisfied: numpy==1.17.4 in /home/pyhe/.local/lib/python3.7/site-packages (from read-until==3.0.0->uncalled==2.3.0) (1.17.4)
Requirement already satisfied: grpcio~=1.37 in /home/pyhe/.local/lib/python3.7/site-packages (from minknow-api>=5.0->uncalled==2.3.0) (1.62.0)
Requirement already satisfied: protobuf~=3.15 in /home/pyhe/.local/lib/python3.7/site-packages (from minknow-api>=5.0->uncalled==2.3.0) (3.20.3)
Requirement already satisfied: packaging>=15.0 in /home/pyhe/anaconda3/lib/python3.7/site-packages (from minknow-api>=5.0->uncalled==2.3.0) (17.1)
Requirement already satisfied: pyrfc3339~=1.1 in /home/pyhe/anaconda3/lib/python3.7/site-packages/pyRFC3339-1.1-py3.7.egg (from minknow-api>=5.0->uncalled==2.3.0) (1.1)
Requirement already satisfied: pyparsing>=2.0.2 in /home/pyhe/anaconda3/lib/python3.7/site-packages (from packaging>=15.0->minknow-api>=5.0->uncalled==2.3.0) (2.2.0)
Requirement already satisfied: six in /home/pyhe/anaconda3/lib/python3.7/site-packages (from packaging>=15.0->minknow-api>=5.0->uncalled==2.3.0) (1.11.0)
Requirement already satisfied: pytz in /home/pyhe/anaconda3/lib/python3.7/site-packages (from pyrfc3339~=1.1->minknow-api>=5.0->uncalled==2.3.0) (2018.5)
Building wheels for collected packages: uncalled
  Building wheel for uncalled (setup.py) ... done
  Created wheel for uncalled: filename=uncalled-2.3.0-cp37-cp37m-linux_x86_64.whl size=17852663 sha256=0c75b8a8bc33c4e9d493da252501f56a629881a3cea5f2904ab1dd6d928616d1
  Stored in directory: /tmp/pip-ephem-wheel-cache-h0lkfgv5/wheels/25/72/30/2bf1aebc06f010a1ba7b4daad8abd5e2ded479896d13ef8eda
Successfully built uncalled
Installing collected packages: uncalled
Successfully installed uncalled-2.3.0
(uncalled) pyhe@PYHE_VM:~/UNCALLED$ python3 -m uncalled
Traceback (most recent call last):
  File "/home/pyhe/anaconda3/lib/python3.7/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/home/pyhe/anaconda3/lib/python3.7/runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/home/pyhe/anaconda3/lib/python3.7/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/pyhe/UNCALLED/uncalled/__init__.py", line 1, in <module>
    from _uncalled import *
ImportError: /home/pyhe/anaconda3/lib/python3.7/site-packages/_uncalled.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZNSt7__cxx1119basic_ostringstreamIcSt11char_traitsIcESaIcEEC1Ev
`

**Comment by peiyihe** [comment]
Hi Sam,

I have also another questions that have bothered me for a long time, for I notice the raw signal from my fast5 ranges from 300 to  500, while the value of k mer model from ONT of R9.4 is almost around 100. And I notice in your paper UNCALLED, you mention the normalization step, but I'm not very clear how to do the normalization. It seems that you don't use such a step in UNCALLED.

Thank you very much for taking the time to help me understand these details.

![image](https://github.com/skovaka/UNCALLED/assets/52478488/65d31303-3ef4-43dc-8458-8f62d3e437f6)

**Comment by skovaka** [comment]
Sorry you're still having problems. Just to make sure it's not a conda issue, could you try deactivating your conda environment (conda deactivate) and re-install it normally, which should install it to `$HOME/.local/`. If that doesn't work, it's probably an issue with one of the C++ libraries, which is weird since we have the same GCC version. The only other difference is our python versions (mine is 3.8), but that shouldn't make a difference. I do have a vague idea about a potential C++ issue, so let me know how it goes.

UNCALLED's normalization is based on the "method of moments", where you linearly scale the events so the mean and standard deviation is equal to that of the pore model. The most basic version of this is something like:
```
scale = model_stdv / event_stdv
shift = model_mean - (scale * event_mean)
norm_events = (events * scale) + shift
```
This works best for long, non-random sequence. To handle short read segments UNCALLED stores a buffer of signal for each pore, maintained between reads, and uses those values for normalization. This is briefly described in the 3rd paragraph of methods in the paper, although I definitely could have added more detail. I was inspired by Nanocall, an early ONT basecaller which describes the basic process better (section 3.4): https://academic.oup.com/bioinformatics/article/33/1/49/2525680

**Comment by peiyihe** [comment]
Hi Sam,

Thanks for your reply again! But I'm still a little bit confused about model_stdv and model_mean，because I don't find a model mean and std in ONT's k-mer model, they are like below. So I just calculate the mean value of these level_mean as model_mean and mean value of these level_stdv as model_stdv? Thank you very much!


kmer	level_mean	level_stdv	sd_mean	sd_stdv	weight
AAAAAA	86.486336	1.517846	0.941478	0.609357	4739.559092
AAAAAC	83.948838	1.517846	1.077051	0.745608	3403.762207
AAAAAG	85.475368	1.517846	0.953434	0.621001	3553.658043
AAAAAT	84.423907	1.517846	1.106077	0.775951	3909.663587
AAAACA	77.097281	1.705015	1.296857	0.936213	2630.415221

**Comment by peiyihe** [comment]
And I read Nanocall, it mentions that "if event i corresponds to context k", but I think for UNCALLED if we don't do normalization first, it seems impossible to know context k?
![image](https://github.com/skovaka/UNCALLED/assets/52478488/09bb492d-ca4d-4424-882c-eea82c32e83d)

**Comment by skovaka** [comment]
UNCALLED only uses the "level_mean" column for normalization, so I was referring to the mean and standard deviation of the entire "level_mean" column. The terminology is confusing because we are computing means and standard deviations of event-level means and standard deviations. Each event (a group of raw samples) is summarized by a mean and stdv, which I label `event.mean` and `event.stdv`. UNCALLED only considers the `event.mean`, and therefore does not normalize `event.stdv`. "level_mean" and "level_stdv" refer to the mean and standard deviation of the expected value of `event.mean` for each k-mer, so we could instead call them `event.mean.mean` and `event.mean.stdv`, which UNCALLED uses to compute k-mer match probabilities. "sd_mean" and "sd_stdv" could be re-labeled `event.stdv.mean` and `event.stdv.stdv`, which tools like [Nanopolish](https://github.com/jts/nanopolish) use to model the event-level noise, but it is ignored by UNCALLED

**Comment by peiyihe** [comment]
And also I notice you have another project named "event_detector", because I want to get the normalization event value from raw signal. I'm not sure to use UNCALLED or event_detector or something else, would you mind sharing some suggestions.

Meanwhile, UNCALLED seems to choose a 5 mer model, while it seems not in kmer models from ONT(https://github.com/nanoporetech/kmer_models/tree/master/legacy)

**Comment by peiyihe** [comment]
And by the way! Thanks for your help again! I have run UNCALLED successfully. I just say what I have done, maybe other people would have same probIem.I close conda, and I don't install pip3, so I install pip3, and install UNCALLED, then success. And my python version is 3.8, I don't know whether it has influenced the result haha. 

And still some little problem, but it seems not very important for me. ERROR: read-until 3.0.0 has requirement numpy==1.17.4, but minknow-api 5.8.1 has requirement numpy~=1.21.

**Comment by skovaka** [comment]
"event_detection" was an old standalone version of the UNCALLED event detector, which didn't include normalization. Your timing is good though, we just released [uncalled4](https://github.com/skovaka/uncalled4), which can accomplish what you want! 

Uncalled4 is mainly a command line signal aligner, similar to Nanopolish or Tombo, but you can also use it as a python module. The module is not documented or very user-friendly (yet), but the following code should give you normalized events from an array of input signal (don't use `pip install uncalled4`, install directly from the repo since I just added some python bindings):
```
from uncalled4 import PoreModel, Config, EventDetector, SignalProcessor
m = PoreModel("dna_r9.4.1_400bps_6mer") #or "dna_r10.4.1_400bps_9mer", "rna_r9.4.1_70bps_5mer", custom TSV file
c = Config()
c.event_detector = EventDetector.PRMS_450BPS #or EventDetector.PRMS_70BPS
sp = SignalProcessor(m,c)
read = sp.process_signal(signal, normalize=True) #signal should be numpy array/list of un-normalized raw sample values

print(read.events["mean"])    #event current means
print(read.events["stdv"])    #event current stdvs
print(read.events["start"])   #event sample starts
print(read.events["length"])  #event sample lengths
print(read.signal)            #normalized raw signal (using method-of-moments)
```
The signal processor performs event detection and normalization using the "method of moments" I described earlier, based on the picoamp values in the the pore model provided. You can change the normalization target mean and standard deviation, for example to have mean=0 and stdv=1, by adding this after initialization: `sp.set_norm_tgt(0, 1) #mean,stdv`

Hope that works for you! If you have any other questions, could you start an issue in the [Uncalled4 repo](https://github.com/skovaka/uncalled4)?
