### ISSUE TITLE
PC spec for realtime run?

### ISSUE THREAD

**Issue by cgjosephlee** [skovaka/UNCALLED#6]
What kind of computing resource do I need to run in realtime?
I'm working on a quad-core i7-4790 cpu, 32Gb ram, 1Tb ssd PC. How do I know if this is applicable for a realtime run?

I tried `uncalled map` 40k reads to a single 26 mb chromosome of a 180 mb genome, mimicking the enrichment mode. It took ~90m to finish, and I found this is much slower than the result in paper (but different in genome size).
```
$ uncalled pafstats test.out.paf
Summary: 40009 reads, 5109 mapped (12.77%)

Speed            Mean    Median
BP per sec:   4206.46   4065.79
BP mapped:     875.58    452.00
MS to map:     229.15    116.13
```

**Comment by skovaka** [comment]
Hi,

It looks like your CPU has only has 4 cores, which isn't ideal since UNCALLED works better with more cores, although you could still get good results. Did you run with more than one thread? I'd recommend using 8 threads for you CPU (add the "-t 8" option). 

Do you expect all of your 40k reads to align? If so then the 12.77% alignment rate is concerning. Otherwise I recommend separating your reads into those you expect to align (TPs) and those you don't (FPs). TPs should be much quicker to align because the algorithm stops as soon as it finds a location. When running in realtime you set a cutoff of when to give up on a read so you don't spend too much time on those that don't align.

Finally, the bp/sec speed is a bit low, so I'd recommend doing a few rounds of repeat masking (see the "masking/" subdirectory). I suspect there are some low complexity regions in your chromosome that's slowing you down. This could also help with your alignment rate.

Hope that helps!
Sam

**Comment by cgjosephlee** [comment]
Thank you for the quick reply!

> It looks like your CPU has only has 4 cores, which isn't ideal since UNCALLED works better with more cores, although you could still get good results. Did you run with more than one thread? I'd recommend using 8 threads for you CPU (add the "-t 8" option).

Yes, since it is a 4c8t cpu, I'm using `-t 8` option. Would you please share your ideal spec of running UNCALLED in realtime?

> Do you expect all of your 40k reads to align? If so then the 12.77% alignment rate is concerning. Otherwise I recommend separating your reads into those you expect to align (TPs) and those you don't (FPs). TPs should be much quicker to align because the algorithm stops as soon as it finds a location. When running in realtime you set a cutoff of when to give up on a read so you don't spend too much time on those that don't align.

And yes, I used only one chromosome instead of whole genome as reference, so the alignment rate is quite rational to me.

> Finally, the bp/sec speed is a bit low, so I'd recommend doing a few rounds of repeat masking (see the "masking/" subdirectory). I suspect there are some low complexity regions in your chromosome that's slowing you down. This could also help with your alignment rate.

I will try to do masking and run again. When doing so, I found that the suggested kmer length of 10 is sometimes problematic, an odd number like 11 would be good.

Best,
Joseph

**Comment by skovaka** [comment]
Hi,

Sorry for the delay. Unfortunately we don't know what the minimal system requirements are. The Xeon Gold 6136 is certainly not required, but in general more cores is better. We've done some testing using only 8 cores and got good results, but it very much depends on your sample and flowcell conditions. Hopefully we can give better guidelines in the future, and I would be very interested to hear how your run goes if you do it.

For masking I would recommend doing as much as possible up until your mapping rate (true positive) starts to reduce. For our Xeon Gold ~6kbp/sec is more than fast enough, but we need to do more testing to get a better idea of the limits. Again, I'll never be able give an absolute minimum bp/sec because the requirements change with your number of cores, sample, and flowcell conditions, but I'm very interested to hear about results running on lower-end CPUs than ours.

Best of luck,
Sam
